server:
  port: 10321

spring:
  application:
    name: consul-client-consumer

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        service-name: consul-client-provider
        instance-id:  consul-client-provider-10321
        heartbeat:
          enabled: true

